// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TierType } from "./TierType";

/**
 * Access status for content (Section 22.3).
 */
export type AccessStatus = { has_access: boolean, tier_type: TierType | null, expires_at: bigint | null, can_redownload: boolean, };
