// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Activity event (Section 22.2).
 */
export type ActivityEvent = { event_type: string, timestamp: bigint, actor_display_name: string | null, content_title: string | null, amount_seeds: bigint | null, };
