// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentManifest } from "./ContentManifest";

/**
 * Catalog diff response (Section 22.11).
 */
export type CatalogDiffResponse = { msg_type: number, added: Array<ContentManifest>, tombstoned: string[], current_catalog_hash: string, };
