// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catalog diff request (Section 22.11).
 */
export type CatalogDiffRequest = { msg_type: number, group_id: string, last_known_epoch: number, last_known_catalog_hash: string, };
