// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NatStatus } from "./NatStatus";

/**
 * Circuit metrics (Section 22.5).
 */
export type CircuitMetrics = { active_circuits: number, circuits_rotated_24h: number, avg_latency_ms: number, relay_count_known: number, nat_traversal_status: NatStatus, };
