// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IntroPointEntry } from "./IntroPointEntry";

/**
 * Contact exchange token for establishing bidirectional contacts (Section 22.6).
 */
export type ContactExchangeToken = { ephemeral_x25519_pk: string, ephemeral_mlkem768_ek: string, intro_points: Array<IntroPointEntry>, ttl_hours: number, created_at: bigint, pik_sig: string, };
