// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingTier } from "./PricingTier";

/**
 * Content manifest (Section 22.3).
 */
export type ContentManifest = { 
/**
 * Merkle root.
 */
content_hash: string, title: string, description: string | null, 
/**
 * Max 5 tags.
 */
tags: Array<string>, 
/**
 * Max 4, min 1.
 */
pricing: Array<PricingTier>, creator_pik: string, group_id: string, successor_hash: string | null, 
/**
 * BLAKE3::hash(decryption_key).
 */
key_commitment: string, total_size_bytes: bigint, chunk_count: number, force_macro: boolean, published_at: bigint, pow_proof: string, 
/**
 * Creator's PIK signature.
 */
sig: string, };
