// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-content earning detail (Section 22.3).
 */
export type ContentEarning = { content_hash: string, title: string, earnings_all_time: bigint, earnings_this_epoch: bigint, purchase_count: number, };
