// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SingleReport } from "./SingleReport";

/**
 * Content report (Section 22.2).
 */
export type ContentReport = { content_hash: string, content_title: string, creator_display_name: string, reports: Array<SingleReport>, };
