// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A contact entry (Section 22.1).
 */
export type Contact = { pik_hash: string, display_name: string, profile_key: string, added_at: bigint, last_seen_epoch: bigint, };
