// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoverTrafficMode } from "./CoverTrafficMode";

/**
 * Cover traffic metrics (Section 22.5).
 */
export type CoverTrafficMetrics = { current_mode: CoverTrafficMode, lambda_p: number, lambda_l: number, lambda_d: number, bandwidth_kbps: number, mode_dwell_remaining_s: number, };
