// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deprecation tombstone for handles (Section 22.4).
 */
export type DeprecationTombstone = { handle: string, deprecated_at: bigint, successor_handle: string | null, 
/**
 * Fixed: 30 days.
 */
tombstone_ttl_days: number, sig: string, };
