// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadState } from "./DownloadState";

/**
 * Download progress (Section 22.9).
 */
export type DownloadProgress = { content_hash: string, total_bytes: bigint, downloaded_bytes: bigint, chunks_complete: number, chunks_total: number, state: DownloadState, error: string | null, };
