// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentEarning } from "./ContentEarning";

/**
 * Earnings report for a Space (Section 22.3).
 */
export type EarningsReport = { group_id: string, 
/**
 * All-time earnings in micro-seeds.
 */
total_all_time: bigint, 
/**
 * This epoch earnings in micro-seeds.
 */
this_epoch: bigint, owner_share: bigint, creator_share: bigint, abr_share: bigint, per_content: Array<ContentEarning>, };
