// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoSrvEntry } from "./PoSrvEntry";

/**
 * Epoch state (Section 22.10).
 */
export type EpochState = { epoch: number, reward_per_token: bigint, total_vys_staked: bigint, fee_pool_balance: bigint, 
/**
 * Poseidon Merkle root.
 */
holder_balances_root: string, 
/**
 * BLAKE3 of Bloom filter snapshot.
 */
nullifier_bloom_hash: string, 
/**
 * Top 100 (or quorum size).
 */
posrv_rankings: Array<PoSrvEntry>, 
/**
 * FROST group signature.
 */
quorum_sig: string, };
