// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Receipt flush statistics (Section 22.3).
 */
export type FlushStats = { receipts_flushed: number, seeds_minted: bigint, epoch: bigint, };
