// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenesisAllocation } from "./GenesisAllocation";
import type { MultisigEntry } from "./MultisigEntry";

/**
 * Genesis manifest (Section 22.8).
 */
export type GenesisManifest = { genesis_epoch: bigint, 
/**
 * 1,000,000 Seeds in micro-seeds.
 */
total_supply: bigint, allocations: Array<GenesisAllocation>, 
/**
 * Published for transparency.
 */
nullifiers: string[], 
/**
 * 5-of-5.
 */
multisig_sigs: Array<MultisigEntry>, };
