// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Genesis allocation (Section 22.8).
 */
export type GenesisAllocation = { name: string, 
/**
 * In micro-seeds.
 */
amount: bigint, 
/**
 * None for immediate.
 */
vest_months: number | null, 
/**
 * e.g. "3-of-5".
 */
multisig_threshold: string, };
