// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitePermission } from "./InvitePermission";
import type { PublishPolicy } from "./PublishPolicy";

/**
 * Space settings (Section 22.2).
 */
export type GroupSettings = { invite_permission: InvitePermission, publish_policy: PublishPolicy, };
