// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRole } from "./MemberRole";
import type { SpaceTemplate } from "./SpaceTemplate";

/**
 * Summary of a Space for listing views (Section 22.2).
 */
export type GroupSummary = { group_id: string, name: string, icon: string | null, template: SpaceTemplate, is_host: boolean, role: MemberRole, member_count: number, last_activity_at: bigint, unread: boolean, pinned: boolean, };
