// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Guardian status for recovery contacts (Section 22.1).
 */
export type GuardianStatus = { contact_pik: string, display_name: string, last_heartbeat_epoch: bigint, 
/**
 * True if heartbeat within 30 days.
 */
is_healthy: boolean, days_since_heartbeat: number, };
