// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandleStatus } from "./HandleStatus";

/**
 * Handle info (Section 22.4).
 */
export type HandleInfo = { handle: string, registered_at: bigint, last_refreshed: bigint, status: HandleStatus, };
