// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Handle registration (Section 22.4).
 */
export type HandleRegistration = { handle: string, registered_at: bigint, 
/**
 * 7 days from registration; auto-refreshed.
 */
expires_at: bigint, };
