// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identity proof types (Section 22.4).
 */
export type IdentityProof = { "type": "handle_proof", handle_signing_pk: string, sig: string, } | { "type": "contact_proof", pik_hash: string, sig: string, };
