// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdentityProof } from "./IdentityProof";

/**
 * Identity reveal for Whisper (Section 22.4).
 */
export type IdentityReveal = { handle: string | null, display_name: string | null, proof: IdentityProof, };
