// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Introduction point entry (Section 22.4).
 */
export type IntroPointEntry = { node_id: string, auth_key: string, };
