// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Invite information (Section 22.2).
 */
export type InviteInfo = { invite_hash: string, creator_flag: boolean, uses_limit: number | null, uses_consumed: number, ttl_days: number, created_at: bigint, expires_at: bigint, is_expired: boolean, };
