// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

/**
 * Log entry (Section 22.5).
 */
export type LogEntry = { timestamp: bigint, level: LogLevel, module: string, message: string, };
