// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MpcStatus } from "./MpcStatus";

/**
 * MPC session info (Section 22.3).
 */
export type MpcSession = { session_id: string, target_api: string, status: MpcStatus, };
