// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification settings (Section 22.9).
 */
export type NotificationSettings = { mute_all: boolean, 
/**
 * Unix timestamp.
 */
mute_until: bigint | null, notify_purchases: boolean, notify_joins: boolean, notify_reports: boolean, };
