// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Nullifier gossip message (Section 22.10).
 */
export type NullifierGossipMsg = { msg_type: number, epoch: number, nullifiers: string[], source_quorum_sig: string | null, hop_count: number, msg_id: string, };
