// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ownership transfer record (Section 22.11).
 */
export type OwnershipTransferRecord = { new_owner_pik: string, initiated_at: bigint, 
/**
 * initiated_at + 7 days.
 */
completes_at: bigint, };
