// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemberRole } from "./MemberRole";

/**
 * Peer profile within a Space (Section 22.1).
 */
export type PeerProfile = { pik_hash: string, display_name: string, role: MemberRole, joined_at: bigint, };
