// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PIK metadata (Section 22.1).
 */
export type PikMeta = { pik_hash: string, created_at: bigint, encrypted_key_path: string, argon2id_salt: string, };
