// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Platform = "macos-arm64" | "macos-x86-64" | "windows-x86-64" | "linux-x86-64" | "android-arm64" | "ios-arm64";
