// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform } from "./Platform";

/**
 * Platform-specific binary hash (Section 22.8).
 */
export type PlatformHash = { platform: Platform, blake3_hash: string, size_bytes: bigint, };
