// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PorStatus } from "./PorStatus";

/**
 * PoR submission status (Section 22.5).
 */
export type PorSubmissionStatus = { status: PorStatus, epoch: bigint, proof_size_bytes: number, proving_time_ms: number, };
