// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PoSrv ranking entry (Section 22.10).
 */
export type PoSrvEntry = { pik_hash: string, posrv_score: number, };
