// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TierType } from "./TierType";

/**
 * Pricing tier (Section 22.3).
 */
export type PricingTier = { tier_type: TierType, 
/**
 * Price in micro-seeds.
 */
price_seeds: bigint, 
/**
 * Days for rental tiers.
 */
rental_days: number | null, };
