// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Profile key exchange payload (Section 22.1).
 */
export type ProfileKeyExchange = { 
/**
 * 256-bit profile key for encrypted profile lookup.
 */
profile_key: string, 
/**
 * Encrypted with recipient's ephemeral session key.
 */
display_name_ciphertext: string, 
/**
 * Ed25519 from sender's PIK, over profile_key.
 */
sig: string, };
