// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TierType } from "./TierType";

/**
 * Purchase record (Section 22.3).
 */
export type PurchaseRecord = { content_hash: string, title: string, tier_type: TierType, 
/**
 * Price in micro-seeds.
 */
price_paid: bigint, purchased_at: bigint, 
/**
 * None for permanent.
 */
expires_at: bigint | null, 
/**
 * Local only, never transmitted.
 */
receipt_secret: string, };
