// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TierType } from "./TierType";

/**
 * Receipt info for blind receipt management (Section 22.3).
 */
export type ReceiptInfo = { content_hash: string, receipt_id: string, tier_type: TierType, last_republished_epoch: bigint, expires_at: bigint | null, };
