// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefundState } from "./RefundState";

/**
 * Refund status (Section 22.3).
 */
export type RefundStatus = { status: RefundState, refund_amount: bigint | null, epoch: bigint, };
