// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relay descriptor (Section 22.10).
 */
export type RelayDescriptor = { node_id: string, pik_hash: string, x25519_pk: string, mlkem768_ek: string, relay_epoch: number, posrv_score: number, ip_addr: string, as_number: number, country_code: string, bandwidth_cap_mbps: number, uptime_epochs: number, sig: string, };
