// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relay receipt for anti-spam accounting (Section 22.4).
 */
export type RelayReceipt = { relay_epoch: number, packet_hash: string, relayer_node_id: string, next_hop_node_id: string, sig: string, };
