// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentManifest } from "./ContentManifest";
import type { RenderedSection } from "./RenderedSection";
import type { SpaceTemplate } from "./SpaceTemplate";

/**
 * Rendered layout for the UI (Section 22.9).
 */
export type RenderableLayout = { layout_type: SpaceTemplate, rendered_sections: Array<RenderedSection>, content_items: Array<ContentManifest>, };
