// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionType } from "./SectionType";

/**
 * Rendered section (Section 22.9).
 */
export type RenderedSection = { section_type: SectionType, title: string | null, content_hashes: string[], };
