// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revenue split (Section 22.8).
 */
export type RevenueSplit = { owner_pct: number, pub_pct: number, 
/**
 * Must sum to 100.
 */
abr_pct: number, };
