// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revenue split change proposal (Section 22.3).
 */
export type RevenueSplitChangeProposal = { group_id: string, sequence: number, proposed_owner_pct: number, proposed_pub_pct: number, proposed_abr_pct: number, effective_at: bigint, broadcast_at: bigint, owner_sig: string, };
