// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultisigEntry } from "./MultisigEntry";

/**
 * Rollback manifest (Section 22.8).
 */
export type RollbackManifest = { 
/**
 * Version to rollback to.
 */
target_version: string, reason: string, 
/**
 * 0-day timelock allowed.
 */
activation_epoch: bigint, 
/**
 * 3-of-5 minimum.
 */
multisig_sigs: Array<MultisigEntry>, };
