// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service receipt for chunk serving (Section 22.10).
 */
export type ServiceReceipt = { server_node_id: string, chunk_id: string, requester_circuit_id: string, bytes_served: number, timestamp: bigint, relay_epoch: number, nonce: string, requester_ack: string, server_sig: string, };
