// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportReason } from "./ReportReason";

/**
 * Individual report entry (Section 22.2).
 */
export type SingleReport = { 
/**
 * Salted pseudonym (Section 16.7). NOT reporter PIK.
 */
reporter_hash: string, reason: ReportReason, detail: string | null, timestamp: bigint, };
