// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EarningsTrend } from "./EarningsTrend";

/**
 * Space statistics (Section 22.2).
 */
export type SpaceStats = { total_members: number, total_creators: number, total_moderators: number, total_content_items: number, total_earnings_all_time: bigint, earnings_this_epoch: bigint, earnings_trend: EarningsTrend, pending_reports: number, };
