// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvitePermission } from "./InvitePermission";
import type { OwnershipTransferRecord } from "./OwnershipTransferRecord";
import type { PublishPolicy } from "./PublishPolicy";
import type { RevenueSplitChangeProposal } from "./RevenueSplitChangeProposal";
import type { SpaceTemplate } from "./SpaceTemplate";

/**
 * Space manifest (Section 22.11).
 */
export type SpaceManifest = { group_id: string, name: string, icon_hash: string | null, template: SpaceTemplate, accent_color: string, host_pik: string, publish_policy: PublishPolicy, invite_permission: InvitePermission, owner_pct: number, pub_pct: number, abr_pct: number, creator_piks: string[], moderator_piks: string[], member_count: number, created_at: bigint, updated_at: bigint, layout_manifest_hash: string | null, pending_transfer: OwnershipTransferRecord | null, pending_split_change: RevenueSplitChangeProposal | null, version: number, host_sig: string, };
