// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Space template types.
 */
export type SpaceTemplate = "storefront" | "forum" | "newsfeed" | "gallery" | "library";
