// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Throttle status for Whisper anti-spam (Section 22.4).
 */
export type ThrottleStatus = { session_msg_count: bigint, current_tier: string, receipts_required: number, global_hourly_count: bigint, global_surcharge: number, total_cost: number, receipts_accumulated: number, is_contact_exempt: boolean, };
