// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of timelocked actions.
 */
export type TimelockAction = "recovery" | "ownership_transfer" | "revenue_split";
