// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelockAction } from "./TimelockAction";

/**
 * Timelock status for delayed operations (Section 22.1).
 */
export type TimelockStatus = { action: TimelockAction, initiated_at: bigint, completes_at: bigint, can_veto: boolean, is_complete: boolean, };
