// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update status (Section 22.5).
 */
export type UpdateStatus = { current_version: string, available_version: string | null, manifest_hash: string | null, activation_epoch: bigint | null, is_mandatory: boolean, };
