// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelayReceipt } from "./RelayReceipt";
import type { WhisperMsgType } from "./WhisperMsgType";

/**
 * Whisper message (Section 22.4).
 */
export type WhisperMessage = { sequence: bigint, timestamp: bigint, msg_type: WhisperMsgType, body: string, relay_receipts: Array<RelayReceipt>, nonce: string, tag: string, };
