// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whisper counterparty info (Section 22.4).
 */
export type WhisperCounterparty = { revealed_handle: string | null, revealed_display_name: string | null, is_contact: boolean, is_verified: boolean, };
