// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whisper target (Section 22.4).
 */
export type WhisperTarget = { "type": "handle" } & string | { "type": "contact" } & string;
