// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionState } from "./SessionState";
import type { WhisperCounterparty } from "./WhisperCounterparty";

/**
 * Whisper session summary (Section 22.4).
 */
export type WhisperSessionSummary = { session_id: string, counterparty: WhisperCounterparty, started_at: bigint, last_message_at: bigint, unread_count: number, state: SessionState, };
