// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whisper ping for missed messages (Section 22.4).
 */
export type WhisperPing = { target_addr: string, timestamp: bigint, ping_id: string, };
