// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whisper message types (Section 22.4).
 */
export type WhisperMsgType = { "type": "text" } | { "type": "seed_transfer", tx_hash: string, amount: bigint, } | { "type": "typing" } | { "type": "read_ack" };
