// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All event types (Section 23).
 */
export type EventType = "new_content" | "content_tombstoned" | "member_joined" | "member_left" | "role_changed" | "purchase_complete" | "earnings_update" | "new_report" | "invite_redeemed" | "balance_update" | "receipt_flushed" | "minting_complete" | "refund_processed" | "transfer_received" | "whisper_message" | "whisper_session_start" | "whisper_session_end" | "whisper_typing" | "whisper_read_ack" | "identity_revealed" | "circuit_rotated" | "epoch_transition" | "peer_connected" | "peer_disconnected" | "por_challenge_received" | "update_available" | "guardian_heartbeat" | "daemon_status" | "error_occurred";
