// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Handle status (Section 22.4).
 */
export type HandleStatus = { "type": "active" } | { "type": "deprecated", deprecated_at: bigint, successor_handle: string | null, };
