// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandleStatus } from "./HandleStatus";
import type { IntroPointEntry } from "./IntroPointEntry";

/**
 * Handle descriptor for Whisper reachability (Section 22.4).
 */
export type HandleDescriptor = { handle: string, handle_signing_pk: string, intro_points: Array<IntroPointEntry>, auth_key: string, pq_auth_key: string, registered_at: bigint, refresh_at: bigint, pow_proof: string, status: HandleStatus, sig: string, };
