// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutSection } from "./LayoutSection";
import type { SpaceTemplate } from "./SpaceTemplate";

/**
 * Layout configuration for a Space (Section 22.9).
 */
export type LayoutConfig = { layout_type: SpaceTemplate, sections: Array<LayoutSection>, 
/**
 * Sandboxed CSS subset.
 */
custom_css: string | null, };
