// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionType } from "./SectionType";

/**
 * Layout section (Section 22.9).
 */
export type LayoutSection = { section_type: SectionType, title: string | null, max_items: number | null, filter_tags: Array<string> | null, };
