// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Member role within a Space.
 */
export type MemberRole = "host" | "creator" | "moderator" | "member";
