// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Multisig entry (Section 22.8).
 */
export type MultisigEntry = { 
/**
 * Keyholder index (0-4).
 */
keyholder_index: number, sig: string, };
