// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultisigEntry } from "./MultisigEntry";
import type { PlatformHash } from "./PlatformHash";

/**
 * Upgrade manifest (Section 22.8).
 */
export type UpgradeManifest = { 
/**
 * Semver, e.g. "5.2.0".
 */
version: string, 
/**
 * Must be >= now + 14 days in epochs.
 */
activation_epoch: bigint, platform_hashes: Array<PlatformHash>, changelog_url: string | null, is_mandatory: boolean, 
/**
 * 3-of-5 minimum.
 */
multisig_sigs: Array<MultisigEntry>, published_at: bigint, };
